export const GameSystem = {
  characters: {
    SOPHIA: {
      name: "SOPHIA",
      path: "/src/model/sophia/sophia.fbx",
      animations: [
        "/src/model/sophia/animation/standing.fbx",
        "/src/model/sophia/animation/hiphop1.fbx",
        "/src/model/sophia/animation/hiphop2.fbx",
        "/src/model/sophia/animation/hiphop3.fbx",
        "/src/model/sophia/animation/hiphop4.fbx",
        "/src/model/sophia/animation/hiphop5.fbx",
        "/src/model/sophia/animation/hiphop6.fbx",
        "/src/model/sophia/animation/hiphop7.fbx",
        "/src/model/sophia/animation/hiphop8.fbx",
        "/src/model/sophia/animation/hiphop9.fbx",
        "/src/model/sophia/animation/hiphop10.fbx",
        "/src/model/sophia/animation/hiphop11.fbx",
        "/src/model/sophia/animation/hiphop12.fbx",
        "/src/model/sophia/animation/hiphop13.fbx",
        "/src/model/sophia/animation/hiphop14.fbx",
        "/src/model/sophia/animation/hiphop15.fbx",
        "/src/model/sophia/animation/hiphop16.fbx",
        "/src/model/sophia/animation/hiphop17.fbx",
        "/src/model/sophia/animation/hiphop18.fbx",
        "/src/model/sophia/animation/hiphop19.fbx",
        "/src/model/sophia/animation/hiphop20.fbx",
        "/src/model/sophia/animation/util1.fbx",
        "/src/model/sophia/animation/util2.fbx",
      ],
    },
    JUN: {
      name: "JUN",
      path: "/src/model/jun/jun.fbx",
      animations: [
        "/src/model/jun/animation/standing.fbx",
        "/src/model/jun/animation/hiphop1.fbx",
        "/src/model/jun/animation/hiphop2.fbx",
        "/src/model/jun/animation/hiphop3.fbx",
        "/src/model/jun/animation/hiphop4.fbx",
        "/src/model/jun/animation/hiphop5.fbx",
        "/src/model/jun/animation/hiphop6.fbx",
        "/src/model/jun/animation/hiphop7.fbx",
        "/src/model/jun/animation/hiphop8.fbx",
        "/src/model/jun/animation/hiphop9.fbx",
        "/src/model/jun/animation/hiphop10.fbx",
        "/src/model/jun/animation/hiphop11.fbx",
        "/src/model/jun/animation/hiphop12.fbx",
        "/src/model/jun/animation/hiphop13.fbx",
        "/src/model/jun/animation/hiphop14.fbx",
        "/src/model/jun/animation/hiphop15.fbx",
        "/src/model/jun/animation/hiphop16.fbx",
        "/src/model/jun/animation/hiphop17.fbx",
        "/src/model/jun/animation/hiphop18.fbx",
      ],
    },
  },
  stage: [
    {
      name: "KOREA",
      path: "/src/model/stage/korea/scene.gltf",
      scale: 140,
      position: [100, 900, -2000],
      thumbnail: "/src/img/korea.jpeg",
    },
    {
      name: "RUSSIA",
      path: "/src/model/stage/russia/scene.gltf",
      scale: 200,
      position: [-700, 3360, -1200],
      thumbnail: "/src/img/russia.jpeg",
    },
    {
      name: "FRANCE",
      path: "/src/model/stage/france/scene.gltf",
      scale: 250,
      rotation: [-1.6, 0, 1],
      position: [-2000, -1200, -500],
      thumbnail: "/src/img/france.jpeg",
    },
    {
      name: "JAPAN",
      path: "/src/model/stage/japan/scene.gltf",
      scale: 500,
      position: [0, 0, -700],
      thumbnail: "/src/img/japan.jpeg",
    },
    {
      name: "GERMANY",
      path: "/src/model/stage/germany/scene.gltf",
      scale: 200,
      position: [0, -300, -1200],
      thumbnail: "/src/img/germany.jpeg",
    },
  ],
  position: {
    1: [1],
    2: [-100, 100],
  },
  target: {
    point: 2100,
    perfect: 100,
    cool: 200,
  },
  point: 1000,
};
